# Site settings
title: "Benjamin Rosenbleet"
email: "benbtc@mit.edu"
description: "Clinical Research | Cryptography | Ethics | Bitcoin | Rugby"
url: "https://Rosenbleet.github.io" # Add your URL here
baseurl: "" # Leave this empty

twitter_username: rosenbleet
github_username: rosenbleet
minimal_mistakes_skin: "default"
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: # e.g., America/New_York

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Profile (Sidebar)
author:
  name   : "Benjamin Rosenbleet"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Clinical Research Cryptography Ethics Bitcoin Rugby"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rosenbleet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Rosenbleet"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:benbtc@mit.edu"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rosenbleet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Rosenbleet"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: "single"
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
